### ISSUE TITLE
Question: How many parser types are included apart from the shown in the example?

### ISSUE THREAD

**Issue by pamplins** [bytemechanics/standalone-ignite#17]

**Comment by watarhu** [comment]
I've created a FAQ page into wiki with the answer to this question [FAQ: How many embedded parsers has GenericTextParser?](https://github.com/bytemechanics/standalone-ignite/wiki/FAQ:-How-many-embeded-parsers-has-GenericTextParser%3F).

But to answer directly the current list of embedded parsers are:
* _java.lang.Boolean_
* _java.lang.Character_
* _java.lang.Short_
* _java.lang.Integer_
* _java.lang.Long_
* _java.lang.Float_
* _java.lang.Double_
* _java.math.BigDecimal(with format "#,##0.0#")_
* _java.lang.String_
* _java.time.LocalTime_ (with _java.time.DateTimeFormatter.ISO_TIME_ format)
* _java.time.LocalDate_ (with _java.time.DateTimeFormatter.ISO_DATE_ format)
* _java.time.LocalDateTime_ (with _java.time.DateTimeFormatter.ISO_DATE_TIME_ format)
* _java.lang.Enum_
* _java.nio.file.Path_
